### ISSUE TITLE
How can I check if the transaction is using the read-datasource when it is read-only?

### ISSUE THREAD

**Issue by KimYongHwi** [kwon37xi/replication-datasource#4]
I'm using LazyConnectionDataSourceProxy and ReplicationRoutingDataSource for db replication. 

I want to check if read-datasource is used in case of `@Transaction(readOnly=true)`. 

How can I know?

**Comment by kwon37xi** [comment]
https://github.com/kwon37xi/replication-datasource/blob/master/src/main/java/kr/pe/kwonnam/replicationdatasource/LazyReplicationConnectionDataSourceProxy.java

At line 32, you can see logging `log.debug("current readOnly : {}", readOnly);`.
Enable `DEBUG` level logging for logger `kr.pe.kwonnam.replicationdatasource`, then I guess you can see the logged message.
